const state={theme:localStorage.getItem("pulse-theme")||"minimal",tab:"me",selectedTrackId:"t1",wave:null,overlay:null,playlistRating:128,wavesToday:0};
const me={name:"Аня",gender:"жен",age:26,photos:5};
const playlist=[{id:"t1",title:"Ночной трамвай",artist:"PULSE Radio",likes:42},{id:"t2",title:"Тише",artist:"Север",likes:19},{id:"t3",title:"Дом на холме",artist:"Маяк",likes:33},{id:"t4",title:"После дождя",artist:"Кадр",likes:11},{id:"t5",title:"Пульс",artist:"Аня",likes:7}];
const publicWaves=[{id:"w1",name:"Марк",track:"Неон",likes:86,comments:12},{id:"w2",name:"Лиза",track:"Окно",likes:54,comments:7},{id:"w3",name:"Тимур",track:"Быстрее",likes:21,comments:3}];
const friends={needAccess:[{name:"Кира",reason:"лайкнула трек"}],opened:[{name:"Олег",reason:"доступ открыт"}],accepted:[{name:"Мила",reason:"взаимный лайк"}];
const comments=[{name:"Олег",text:"этот припев держит"},{name:"Кира",text:"оставляю лайк треку"},{name:"Мила",text:"можно следующий эфир"];
const selectedTrack=()=>playlist.find(t=>t.id===state.selectedTrackId)||playlist[0];
function setTheme(theme){state.theme=theme;document.documentElement.setAttribute("data-theme",theme);localStorage.setItem("pulse-theme",theme)}
function remainLabel(){if(!state.wave)return"";const ms=Math.max(0,state.wave.endsAt-Date.now());const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4),s=Math.floor(ms%6e4/1e3);return h+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
function startWave(){if(!playlist.length)return;if(state.wave){state.overlay="wave";render();return}if(state.wavesToday>=3){alert("Бесплатно 3 волны в день. Дальше — подписка.");return}const track=selectedTrack();state.wavesToday+=1;state.wave={track,likes:track.likes,startedAt:Date.now(),endsAt:Date.now()+108e5};state.overlay="wave";render()}
function renderMe(){const photos=Array.from({length:me.photos},(_,i)=>`<div class="ph ${i===0?"main":""}"></div>`).join("");const tracks=playlist.map(t=>`<button class="track ${t.id===state.selectedTrackId?"active":""}" data-pick="${t.id}"><div><div>${t.title}</div><small>${t.artist}</small></div><small>♥ ${t.likes}</small></button>`).join("");return `<div class="photos">${photos}</div><div class="meta"><h1>${me.name}</h1><p>${me.gender} · ${me.age}</p></div><div class="tracks">${tracks}</div><div class="row"><button class="btn" data-act="library">Библиотека</button><button class="btn" data-act="upload">Загрузить свой</button></div><button class="btn-wide" data-act="create-wave">Создать Волну</button><button class="btn-wide ghost" data-act="goto-waves">Поймать Волну</button><p class="rating">Рейтинг плейлиста · ${state.playlistRating} · волн сегодня ${state.wavesToday}/3</p>`}
function renderWaves(){return publicWaves.map(w=>`<article class="card"><b>${w.name}</b><div>${w.track}</div><small>♥ ${w.likes} · ${w.comments} комментариев</small></article>`).join("")}
function renderFriends(){const block=(title,items)=>`<div class="shelf">${title}</div>`+items.map(i=>`<article class="card"><b>${i.name}</b><div>${i.reason}</div></article>`).join("");return block("Нужен доступ",friends.needAccess)+block("Открытые",friends.opened)+block("Друзья",friends.accepted)}
function renderStage(){return `<article class="card"><b>Сцена</b><p>Профиль артиста и клубы появятся после живой волны.</p></article>`}
function renderWaveOverlay(){if(!state.wave)return"";const bars=Array.from({length:28},(_,i)=>`<span style="height:${30+(i*37)%70}%;animation-delay:${i*.04}s"></span>`).join("");const chat=comments.map(c=>`<div class="comment"><b>${c.name}</b><span>${c.text}</span></div>`).join("");return `<section class="overlay"><div class="top"><button class="icon-btn" data-act="close-wave">Закрыть</button><div class="brand">ВОЛНА</div><div></div></div><div class="screen"><div class="wave-art">${bars}</div><h1>${state.wave.track.title}</h1><div class="likes">♥ ${state.wave.likes} лайков трека</div><div class="timer">осталось ${remainLabel()} · один трек до конца эфира</div><div class="comments">${chat}</div></div></section>`}
function render(){setTheme(state.theme);const screens={me:renderMe,waves:renderWaves,friends:renderFriends,stage:renderStage};const titles={me:"Я",waves:"Волны",friends:"Друзья",stage:"Сцена"};const track=selectedTrack();document.getElementById("app").innerHTML=`<div class="app"><div class="top"><div class="brand">PULSE</div><button class="theme-btn" data-act="theme">${state.theme==="minimal"?"Яркая":"Минимал"}</button></div><main class="screen"><div class="shelf">${titles[state.tab]}</div>${screens[state.tab]()}</main><div class="player"><div><b>${track.title}</b><div class="timer" style="margin:0">${state.wave?"в эфире":"не в эфире"}</div></div><button class="icon-btn" data-act="create-wave">▶</button></div><nav class="tabs"><button data-tab="me" class="${state.tab==="me"?"active":""}">Я</button><button data-tab="waves" class="${state.tab==="waves"?"active":""}">Волны</button><button data-tab="friends" class="${state.tab==="friends"?"active":""}">Друзья</button><button data-tab="stage" class="${state.tab==="stage"?"active":""}">Сцена</button></nav>${state.overlay==="wave"?renderWaveOverlay():""}</div>`}
document.getElementById("app").addEventListener("click",e=>{const tab=e.target.closest("[data-tab]");if(tab){state.tab=tab.dataset.tab;render();return}const pick=e.target.closest("[data-pick]");if(pick){state.selectedTrackId=pick.dataset.pick;render();return}const act=e.target.closest("[data-act]")?.dataset.act;if(!act)return;if(act==="theme")setTheme(state.theme==="minimal"?"vivid":"minimal");if(act==="create-wave")startWave();if(act==="goto-waves")state.tab="waves";if(act==="close-wave")state.overlay=null;if(act==="library")alert("Общая библиотека подключится на следующем срезе.");if(act==="upload"){playlist.push({id:"t"+(playlist.length+1),title:"Новый трек",artist:"с устройства",likes:0});state.selectedTrackId=playlist[playlist.length-1].id}render()});
setTheme(state.theme);render();setInterval(()=>{if(state.wave&&state.overlay==="wave"){if(Date.now()>=state.wave.endsAt){state.wave=null;state.overlay=null}render()}},1000);
